# Generated by Django 5.0.2 on 2024-05-07 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('selling_price', models.FloatField()),
                ('discounted_price', models.FloatField()),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('JS', 'Jeans'), ('ST', 'Shirts'), ('TS', 'T-Shirts'), ('PS', 'Pants'), ('HS', 'HAlf-Shirts'), ('LP', 'Ladies-pants'), ('TP', 'Tops'), ('LG', 'Leggings')], max_length=2)),
                ('product_image', models.ImageField(upload_to='product')),
            ],
        ),
    ]
